spring:
  application:
    name: spring_1_8
  shell:
    interactive:
      enabled: true
    script:
      enabled: false
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:librarydb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
